api/urls.py
from django.urls import path

from .views import bbs, BbDetailView, comments, SubRubrics

urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('rubrics/', SubRubrics.as_view()),
    path('bbs/', bbs),
]

bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('social/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))  # запрет на кэширование стилей, пока с ними
    # не закончили
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, BBLogoutView, profile, ChangeUserInfoView, BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail
from .views import profile_bb_detail, profile_bb_add, profile_bb_change, profile_bb_delete

app_name = 'main'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('acconts/profile/<int:rubric_pk>/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),  # по этому пути django по умолчанию перенаправляет после входа
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .models import AdvUser, user_registrated, SuperRubric, SubRubric, Bb, AdditionalImage, Comment


# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        try:
            password1 = self.cleaned_data['password1']
        except KeyError:
            errors = {'password1': ValidationError('', code='password_mismatch')}
            raise ValidationError(errors)
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#


# ----------------------------------------------РУБРИКИ-----------------------------------------------------------#
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None,
                                          label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'
# ----------------------------------------------РУБРИКИ-----------------------------------------------------------#


# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class BbForm(forms.ModelForm):
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput,  # значение в это поле будет заноситься автоматически
        }


AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')
# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#


# ----------------------------------------------КОММЕНТАРИИ-------------------------------------------------------#
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)  # Убираем из формы, т.к. это поле только для админки
        widgets = {
            'bb': forms.HiddenInput,
            'author': forms.HiddenInput,
        }


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки',
                           error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}
# ----------------------------------------------КОММЕНТАРИИ-------------------------------------------------------#

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.db.models import Q

from .models import AdvUser, SubRubric, Bb, Comment
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, BbForm, AIFormSet
from .forms import UserCommentForm, GuestCommentForm
from .utilities import signer


# Create your views here.
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)  # Необходимо сделать выход перед удалением
        messages.add_message(request, messages.SUCCESS, f'Пользователь {request.user.username} удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class BBLoginView(LoginView):
    template_name = 'main/login.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html', context={'username': username})
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template, context={'username': username})


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)

    paginator = Paginator(bbs, 3)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)

    context = {
        'bbs': page.object_list,
        'page': page,
    }
    return render(request, 'main/profile.html', context)
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#


# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})

    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'rubric': rubric,
        'page': page,
        'bbs': page.object_list,
        'form': form,
    }
    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):

    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()  # Список дополнительных изображений
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)

    if request.method == 'POST':
        if request.user.is_superuser and request.POST.get('comment_delete', None):
            comment_pk = request.POST.get('comment_delete', None)
            comment = Comment.objects.get(pk=comment_pk)
            comment.delete()
            messages.add_message(request, messages.SUCCESS, 'Комментарий удален')
            return HttpResponseRedirect(f'/{rubric_pk}/{pk}')
        else:
            c_form = form_class(request.POST)
            if c_form.is_valid():
                c_form.save()
                messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
                return HttpResponseRedirect(f'/{rubric_pk}/{pk}')
            else:
                form = c_form
                messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {
        'bb': bb,
        'ais': ais,
        'comments': comments,
        'form': form,
    }
    return render(request, 'main/detail.html', context)


@login_required
def profile_bb_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)

    if request.method == 'POST':
        comment_pk = request.POST.get('comment', None)
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Комментарий удален')

    ais = bb.additionalimage_set.all()  # Список дополнительных изображений
    comments = Comment.objects.filter(bb=pk, is_active=True)
    context = {
        'bb': bb,
        'ais': ais,
        'comments': comments,
    }
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)  # все доп.иллюстрации после сохранения
            # окажутся связанными с объявлением
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = BbForm(initial={
            'author': request.user.pk,
        })
        formset = AIFormSet()
        context = {
            'form': form,
            'formset': formset,
        }
        return render(request, 'main/profile_bb_add.html', context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление отредактировано')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'main/profile_bb_change.html', context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {
            'bb': bb
        }
        return render(request, 'main/profile_bb_delete.html', context)
# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {
        'bbs': bbs,
    }
    return render(request, 'main/index.html', context)

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Этот метатег необходим для работы Bootstrap -->
        <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
        {% bootstrap_css %}
        <!-- Привязка к таблице стилей Bootstrap -->
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        <!-- в css будут специфичные для сайта стили -->
        {% bootstrap_javascript jquery='slim' %}
        <!-- Привязываем файлы веб-сценариев с программным годом Bootstrap. также привязываем сокращенную редакцию
        библиотеки jQuery, без которой не заработает созданное нами раскрывающееся меню (AJAX и анимация
        использоваться не будет - поэтому полная редакция jQuery не нужна -->
    </head>
    <body class="container-fluid">
    <!-- Стилевой класс container-fluid необходимо привязать к каждому тегу, чье содержимое будет
    верстаться с помощью Bootstrap-->
        <header class="mb-4">
            <h1 class="display-1 text-center">Объявления</h1>
        </header>
        <!-- mb-4 - установит большой отступ снизу. display-1, text-center - увеличенный шрифт и выравнивание
         посередине -->
        <div class="row">
        <!-- Этот код рализует фишку Bootstrap - табличную верстку, без участия таблиц.
        Стилевой класс row вынуждает элемент вести себя как строка таблицы, а стилевой класс col -
        как ячейка в этой строке.
        В данно случае создается стркоа (блок <div>) с единственной ячейкой - маркированным списком.
        Сделано для того, чтобы убрать у создаваемого элемента просветы слева и справа (для красоты) -->

            <ul class="col nav justify-content-end border">
             <!-- Маркированный список. Используется для создания горизонтальной полосы навигации (стилевой
             класс nav. Стилевой класс justify-content-end укажет выровнять пункты полосы навигации по правому краю,
             а класс border создаст рамку вокруг нее -->
                {% if user.is_authenticated %}
                <li class="nav-link">Вы зашли как {{ user.username }}</li>
                {% else %}
                <li class="nav-link">Вы не авторизованы</li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:register' %}">Регистрация</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                       role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
                        <div class="dropdown-divider"></div> <!-- Разделитель -->
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
                    </div>
                </li>
                <!-- Вышележащий код создает в полосе навигации пункт с раскрывающимся меню.-->
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Вход</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:begin' 'vk-oauth2' %}">Войти через ВКонтакте</a>
                </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:other' page='about' %}">О сайте</a></li>
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
                {% for rubric in rubrics %}
                {% ifchanged rubric.super_rubric.pk %}
                <span class="nav-link root font-weight-bold">
                    {{ rubric.super_rubric.name }}
                </span>
                {% endifchanged %}
                <a class="nav-link" href="{% url 'main:by_rubric' pk=rubric.pk %}">{{ rubric.name }}</a>
                {% endfor %}
                <!-- Перебираем все подрубрики из переменной rubrics (создана менеджером контекста
                bboard_context_processor(). Если изменился ключ надрубрики - выводим название надрубрики и
                выводим ссылки на все подрубрики -->
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %} <!-- Всплывающие сообщения -->
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <!-- Снова табличная верстка, но из двух ячеек (<nav>, <section>).
        col-md-auto - ширина ячейки соответствует ширине содержимого.
        nav, flex-column - превращяем ячейку в вертикальную панель навигации в стиле Bootstrap.
        border - рамка.
        root - записан в static/main/style.css
        font-weight-bold - полужирный шрифт
        py-2 - небольшие внутренние отступы -->
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; читатели, 2020 г.</p>
    </footer>
    <!-- "Поддон" сайта. mt-3 - средний внешний отступ сверху -->
    </body>
</html>