api/urls.py
from django.urls import path

from .views import bbs, BbDetailView, comments, SubRubrics

urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('rubrics/', SubRubrics.as_view()),
    path('bbs/', bbs),
]

bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('social/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))  # запрет на кэширование стилей, пока с ними
    # не закончили
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, BBLogoutView, profile, ChangeUserInfoView, BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail
from .views import profile_bb_detail, profile_bb_add, profile_bb_change, profile_bb_delete

app_name = 'main'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('acconts/profile/<int:rubric_pk>/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),  # по этому пути django по умолчанию перенаправляет после входа
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .models import AdvUser, user_registrated, SuperRubric, SubRubric, Bb, AdditionalImage, Comment


# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        try:
            password1 = self.cleaned_data['password1']
        except KeyError:
            errors = {'password1': ValidationError('', code='password_mismatch')}
            raise ValidationError(errors)
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#


# ----------------------------------------------РУБРИКИ-----------------------------------------------------------#
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None,
                                          label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'
# ----------------------------------------------РУБРИКИ-----------------------------------------------------------#


# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class BbForm(forms.ModelForm):
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput,  # значение в это поле будет заноситься автоматически
        }


AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')
# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#


# ----------------------------------------------КОММЕНТАРИИ-------------------------------------------------------#
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)  # Убираем из формы, т.к. это поле только для админки
        widgets = {
            'bb': forms.HiddenInput,
            'author': forms.HiddenInput,
        }


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки',
                           error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}
# ----------------------------------------------КОММЕНТАРИИ-------------------------------------------------------#

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.db.models import Q

from .models import AdvUser, SubRubric, Bb, Comment
from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, BbForm, AIFormSet
from .forms import UserCommentForm, GuestCommentForm
from .utilities import signer


# Create your views here.
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)  # Необходимо сделать выход перед удалением
        messages.add_message(request, messages.SUCCESS, f'Пользователь {request.user.username} удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class BBLoginView(LoginView):
    template_name = 'main/login.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html', context={'username': username})
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template, context={'username': username})


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)

    paginator = Paginator(bbs, 3)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)

    context = {
        'bbs': page.object_list,
        'page': page,
    }
    return render(request, 'main/profile.html', context)
# ----------------------------------------------АВТОРИЗАЦИЯ-------------------------------------------------------#


# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})

    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'rubric': rubric,
        'page': page,
        'bbs': page.object_list,
        'form': form,
    }
    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):

    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()  # Список дополнительных изображений
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)

    if request.method == 'POST':
        if request.user.is_superuser and request.POST.get('comment_delete', None):
            comment_pk = request.POST.get('comment_delete', None)
            comment = Comment.objects.get(pk=comment_pk)
            comment.delete()
            messages.add_message(request, messages.SUCCESS, 'Комментарий удален')
            return HttpResponseRedirect(f'/{rubric_pk}/{pk}')
        else:
            c_form = form_class(request.POST)
            if c_form.is_valid():
                c_form.save()
                messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
                return HttpResponseRedirect(f'/{rubric_pk}/{pk}')
            else:
                form = c_form
                messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {
        'bb': bb,
        'ais': ais,
        'comments': comments,
        'form': form,
    }
    return render(request, 'main/detail.html', context)


@login_required
def profile_bb_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)

    if request.method == 'POST':
        comment_pk = request.POST.get('comment', None)
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Комментарий удален')

    ais = bb.additionalimage_set.all()  # Список дополнительных изображений
    comments = Comment.objects.filter(bb=pk, is_active=True)
    context = {
        'bb': bb,
        'ais': ais,
        'comments': comments,
    }
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)  # все доп.иллюстрации после сохранения
            # окажутся связанными с объявлением
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = BbForm(initial={
            'author': request.user.pk,
        })
        formset = AIFormSet()
        context = {
            'form': form,
            'formset': formset,
        }
        return render(request, 'main/profile_bb_add.html', context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление отредактировано')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'main/profile_bb_change.html', context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {
            'bb': bb
        }
        return render(request, 'main/profile_bb_delete.html', context)
# ----------------------------------------------ОБЪЯВЛЕНИЯ--------------------------------------------------------#


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {
        'bbs': bbs,
    }
    return render(request, 'main/index.html', context)

main/templates/main/activation_done.html
{% extends "layout/basic.html" %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь {{ username }} успешно активирован.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{% extend "layout/basic.html" %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя {{ username }} прошла неудачно.</p>
<p><a hred="{% url 'main:register' %}">Зарегестрироваться повторно</a></p>
{% endblock %}

main/templates/main/by_rubric.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>

<div class="container-fluid mb-2">  <!-- container-fluid - таблица HTML. mb-2 - отступ снизу -->
    <div class="row"> <!-- Строка таблицы -->
        <div class="col">&nbsp;</div> <!-- Строка таблицы. &nbsp; - неразрыный пробел -->
        <form class="col-md-auto form-inline"> <!-- col-md-auto - ячейка с шириной, равной содержимому.
                                                form-inline - вывести элементы управления в 1 строку -->
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>

{% if bbs %}
<ul class="list-unstyled"> <!-- Перечень Bootstrap -->
    {% for bb in bbs %}
    <li class="media my-5 p-3 border"> <!-- my-5 - большие внешние отступы сверху и снизу.
                                        p-3 - внутренние средние отступы со всех сторон. border - рамка -->
        {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}"> <!-- all - from middlewares.bboard_context_processor -->
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="empty-image mr-3" src="{% static 'main/empty.jpg' %}"> <!-- empty-image - from style.css -->
            {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a> </h3>
            <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>

{% bootstrap_pagination page url=keyword %} <!-- url=keyword - при переходе на другую часть пагинатора контроллер
                                            получит это слово и сможет выполнить фильтрацию -->
{% endif %}
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/detail.html
{% extends "layout/basic.html" %}
{% load static %}
{% load bootstrap4 %}
{% block title %}{{ bb.title }} - {{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <a href="{{ bb.image.url }}">
                <img src="{{ bb.image.url }}" class="main-image">
            </a>
        </div>
        <!-- main-image - определен в main/style.css -->
        {% else %}
        <div class="col-md-auto"><img class="main-image" src="{% static 'main/empty.jpg' %}"></div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} руб.</p>

            {% if bb.author.first_name %}
            <p>{{ bb.contacts }} - {{ bb.author.first_name }}</p>
            {% else %}
            <p>{{ bb.contacts }} - {{ bb.author }}</p>
            {% endif %}

            <p class="text-right font-italic">Объявление добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>

{% if ais %}
<div class="d-flex justify-content-start flex-wrap mt-5">
<!-- d-flex - устанавлиает для элемента гибкую разметку, при которой
дочерние элементы выстраиваются внутри родителя по горизонтали.
justify-content-between - указывает, что дочерние элементы (доп. иллюстрации)
должны располагаться внутри родителя на равном расстоянии.
flex-wrap - если не хватит места по гоизонтали - перенести элементы на след. строку.
mt-5 - большой внешний отступ сверху -->
    {% for ai in ais %}
    <div class="mr-2">
        <a href="{{ ai.image.url }}">
            <img class="additional-image" src="{{ ai.image.url }}">
            <!-- additional-image - определен в main/style.css -->
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}

<p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}"Назад></a></p>
<h4 class="mt-5">Новый коментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% if comments %}

<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border"> <!--my-2 - небольшие внешние отступы сверху и снизу.
                                  p-2 - небольшие внутренние отступы со всех сторон -->
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at}}</p>
        <form method="post">
            {% csrf_token %}
            {% if user.is_superuser %}
            <input type="hidden" name="comment_delete" value="{{ comment.pk }}">
            <input type="submit" value="Удалить (как администратор)">
            {% endif %}
        </form>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
<h2>Последние 10 объявлений</h2>

{% if bbs %}
    <ul class="list-unstyled"> <!-- Перечень Bootstrap -->
        {% for bb in bbs %}
        {% url 'main:detail' rubric_pk=bb.rubric.pk pk=bb.pk as url %}
        <li class="media my-5 p-3 border"> <!-- my-5 - большие внешние отступы сверху и снизу.
                                            p-3 - внутренние средние отступы со всех сторон. border - рамка -->
            <a href="{{ url }}{{ all }}"> <!-- all - from middlewares.bboard_context_processor -->
                {% if bb.image %}
                <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                {% else %}
                <img class="empty-image mr-3" src="{% static 'main/empty.jpg' %}"> <!-- empty-image - from style.css -->
                {% endif %}
            </a>
            <div class="media-body">
                <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a> </h3>
                <p class="font-italic">{{ bb.rubric.super_rubric.name }} - {{ bb.rubric.name }}</p>
                <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
                <p class="text-right font-italic">{{ bb.created_at }}</p>
            </div>
        </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
    <p>Здравствйуте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
    <p>Здравствуйте!</p>
    {% endif %}
    <p><a href="{% url 'main:profile_bb_add' %}">Добавить объявление</a></p>
    <h3>Ваши объявления:</h3>

    {% if bbs %}
    <ul class="list-unstyled"> <!-- Перечень Bootstrap -->
        {% for bb in bbs %}
        {% url 'main:profile_bb_detail' rubric_pk=bb.rubric.pk pk=bb.pk as url %}
        <li class="media my-5 p-3 border"> <!-- my-5 - большие внешние отступы сверху и снизу.
                                            p-3 - внутренние средние отступы со всех сторон. border - рамка -->
            <a href="{{ url }}{{ all }}"> <!-- all - from middlewares.bboard_context_processor -->
                {% if bb.image %}
                <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                {% else %}
                <img class="empty-image mr-3" src="{% static 'main/empty.jpg' %}"> <!-- empty-image - from style.css -->
                {% endif %}
            </a>
            <div class="media-body">
                <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a> </h3>
                <p class="font-italic">{{ bb.rubric.super_rubric.name }} - {{ bb.rubric.name }}</p>
                <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
                <p class="text-right font-italic">{{ bb.created_at }}</p>
                <p class="te[t-right mt-2">
                    <a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Исправить</a>
                    <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a>
                </p>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

{% bootstrap_pagination page  %}

{% endblock %}

main/templates/main/profile_bb_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Редактирование объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2>Редактирование объявления</h2>
<form method="post" enctype="multipart/form-data"> <!-- Метод кодирования для отправки файлов -->
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %} <!-- Набор форм -->
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_bb_delete.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>
<p class="text-left font-italic">Удалить объявление {{ bb.title }}?</p>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь {{ username }} был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}